### ISSUE TITLE
study rebase 1.11.29

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#528]
Updates:
- Show room create icon if "UIComponent.roomCreation" is enabled: https://github.com/matrix-org/matrix-react-sdk/pull/10364/files
- Show "Invite" menu option if "UIComponent.sendInvites" is enabled: https://github.com/matrix-org/matrix-react-sdk/pull/10363

- Notifications: inline error message on notifications saving error: https://github.com/matrix-org/matrix-react-sdk/pull/10288

- Improved a11y for Field feedback and Secure Phrase input: https://github.com/matrix-org/matrix-react-sdk/pull/10320

- Fix long display name overflowing reply tile on IRC layout: https://github.com/matrix-org/matrix-react-sdk/pull/10343

I did not find PR that would impact our code negatively.

When trying to do a rebase, I also noticed that something was added in .github/workflows/static_analysis.yaml, related to typescript:

```
    tsc-strict:
        name: Typescript Strict Error Checker
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
            checks: write
        steps:
            - uses: actions/checkout@v3

            - name: Install Deps
              run: "scripts/tchap/install-yarn-linked-repositories.sh"

            - name: Get diff lines
              id: diff
              uses: Equip-Collaboration/diff-line-numbers@df70b4b83e05105c15f20dc6cc61f1463411b2a6 # v1.0.0
              with:
                  include: '["\\.tsx?$"]'

            - name: Detecting files changed
              id: files
              uses: futuratrepadeira/changed-files@96d5fd702a6479d573287ef07381ad59acc390ed # v4.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pattern: '^.*\.tsx?$'

            - uses: t3chguy/typescript-check-action@main
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  use-check: false
                  check-fail-mode: added
                  output-behaviour: annotate
                  ts-extra-args: "--strict --noImplicitAny"
                  files-changed: ${{ steps.files.outputs.files_updated }}
                  files-added: ${{ steps.files.outputs.files_created }}
                  files-deleted: ${{ steps.files.outputs.files_deleted }}
                  line-numbers: ${{ steps.diff.outputs.lineNumbers }}
```
